@base_url = http://localhost:8080

@url_get = {{base_url}}/GetPost
@url_get_id = {{base_url}}/GetUser/test/get
@url_post = {{base_url}}/
@url_put = {{base_url}/1
@url_del = {{base_url}}/1

###
GET {{url_get}} HTTP/1.1

###
GET {{url_get_id}} HTTP/1.1

###
POST {{url_post}} HTTP/1.1
Content-Type: application/json
{
    "test" : "xxx"
}

###
PUT {{url_put}} HTTP/1.1
Content-Type: application/json
{
    "test" : "xxx"
}

###
DELETE {{url_del}} HTTP/1.1